export { default as Login } from './login/Login';
export { default as Home } from './home/Home';
export { default as Customer } from './customer/Customer';
export { default as AddCustomer } from './customer/AddCustomer';
export { default as Sales } from './sales/Sales';
export { default as AddSales } from './sales/AddSales';
export { default as Exercise } from './exercise/Exercise';
export { default as PackageSetting } from './exercise/PackageSetting';
export { default as AssignExercise } from './exercise/AssignExercise';
